### ISSUE TITLE
https://t.me/NEST_BABGiveaway/63283

### ISSUE THREAD

**Issue by rezapras420** [NEST-Protocol/NESTRedEnvelopesBot#6]
Claim error

**Comment by tunogya** [comment]
I found the configuration of this Prize. There are still nearly 2,000 seats available for this Prize. However, the wallet address you bind to holds BAB tokens.

By the way, in order to prevent malicious cheating, although you can use the same address to complete tasks to receive red envelopes, duplicate addresses will be filtered out during settlement.
